### PR TITLE
added config setting to set channel for bot to listen to

### PR DESCRIPTION
**Pull request by hp3721**
This is disabled by default.

### CODE REVIEW

**Comment by architdate** [comment]
Wouldn't this be better handled by discord native permissions? Kind of redundant to have a setting right?

**Comment by hp3721** [comment]
idk but someone asked for it earlier

**Comment by hp3721** [comment]
I could just compile this for them and you wouldn't need to merge.

**Comment by hp3721** [comment]
I could just compile this for them and you wouldn't need to merge.

**Pull request closed without merging**
