### PR TITLE
update pointers 1.3.2 fr this time

### PR DESCRIPTION
**Pull request by GapingWalrus**
0 and 8 look the same soz for the double pr

### CODE REVIEW

**Comment by gutialv23** [comment]
It works! Thanks! You saved my server hahaha
I would like to learn how to update these pointers
If somebody has time to teach me, I the next update I will also work on that :D

**Comment by Aaron456781** [comment]
Has this been updated properly for the new SV update as the guy above me has said it but when I clone the repo its pulling PKHEX core version 23.5.11. I have the most recent PKHEX core in the nuget folder.

**Comment by GapingWalrus** [comment]
> Has this been updated properly for the new SV update as the guy above me has said it but when I clone the repo its pulling PKHEX core version 23.5.11. I have the most recent PKHEX core in the nuget folder.

if you have most recent core just chuck it in the folder with sysbot.exe and itll run

**Comment by lGodHatesMel** [comment]
This is still a pull request so it hasn't been merged and updated. It wont be updated until everything else is updated, as there is no point in updating thing bit by bit when you can just do it all at once unless you know how to do it you self then feel free to, its not that hard.

**Comment by Aaron456781** [comment]
oh ok thanks for clearing that up. I know a lot of people have got there bots back up and running

**Comment by xtheredshirtx** [comment]
I can't seem to get it to update pkhex core to the latest after i build it. Putting the updated .dll in the same folder doesn't seem to fix it for some reason.

**Comment by darthvader1043** [comment]
> I can't seem to get it to update pkhex core to the latest after i build it. Putting the updated .dll in the same folder doesn't seem to fix it for some reason.

Could be 1 of 2 issues. 1 you didn’t build it correctly and don’t have all the files in the folder with the exe or 2 you didn’t build pkhex from git and drop the dll into the folder. 
It does work as i have been running it just fine. Try rebuilding both sysbot with updated pointers (if you don’t want to change the code yourself you can use their git instead) as well as build pkhex from git (it’s different from the downloaded dev build) and drop the dll built from that into the folder. If it still doesn’t work you may need to update your nugt core for pkhex.

**Comment by xtheredshirtx** [comment]
Thanks got that part fixed now but oddly enough now every pokemon is now not legal? Was there something else I was supposed to change? For example I requested Ditto and it said skipping trade.

**Comment by lGodHatesMel** [comment]
There isnt an official update yet,  So not much support will be giving. But a tip is probably need to update the alm core or probably not use the pkhex dll for rhe latest push from evotree. If you dont know how to do that, its best to just wait for official update as ppl just need to be patient

**Comment by xtheredshirtx** [comment]
I figured it out on my own. Those who need a working sysbot for SV trading let me know and ill send it over to you.

**Comment by Aaron456781** [comment]
What did you do to get it working ?

**Comment by xtheredshirtx** [comment]
> What did you do to get it working ?

So you have to update a few more things and now just the pointers. What I did was the following and it worked. 

1. In the scripts where it says PackageReference Include="PKHeX.Core" Version= I changed this to PackageReference Include="PKHeX.Core" Version="23.6.03" /> Make sure to change this in every section that has that listed. 
2. I then went to the sysbot.pokemon>deps>and replaced the pkhex.core.automod.dll with what they posted here. To do this if you haven't before delete it and then right click on deps and select add>existing item and select the downloaded file that is new.
3. Then I rebuilt the solution and it worked.

**Comment by Aaron456781** [comment]
Did you change that code in Visual Studio?

**Comment by Aaron456781** [comment]
Can you send me your working sysbot please. I want to know if it’s my switch playing up on my new PC or if I’m building it wrong

**Comment by SNLabat** [comment]
@xtheredshirtx What's the best way to get in touch with you? I've been banging my head against the wall to get my Raidbot back up and running. Would just uploaded it to a repo to send to you to overwrite with your files, would that work?

**Comment by Aaron456781** [comment]
Will it let you upload a zip through here? Overwriting the files I have will work

**Comment by SNLabat** [comment]
@xtheredshirtx 

[https://drive.google.com/file/d/1PitcC9dOXMJ7LzCns5gEJ2AAmC-tpA-5/view?usp=drive_link](url)

Uploaded it to Google Drive, I'll pull the zip after as to not muddy things up here.

**Comment by GapingWalrus** [comment]
this is not a forum stop using it like one

https://github.com/GapingWalrus/SysBot.NET/releases/tag/v1.3.2

**Comment by Aaron456781** [comment]
its working now thanks

**Comment by kwsch** [comment]
This pull request will eventually be closed with a separate commit containing the correct IsConnectedPointer; still waiting for PKHeX's latest release.

Seeking out forks and custom builds of SysBot.NET can be a bad idea if your overall goal is to just resume sending out hacked Pokémon. Without proper legality support (generating & checking), you'd not only be sending out bad hacks, you could be more easily identified and have online services restricted.

This repo's maintainers (@Lusamine, myself) have preferred to hold off on just merging in updated pointers for two reasons:
1. Legality is not updated for HOME (the PKHeX 23.06.03 release is notably deficient as mentioned in the Discord)
2. Us not updating serves as an anti-spoonfeeding Easter egg of sorts to get people to get involved with the development tasks (finding pointers, updating programs), which provides incentive for the community to grow outside of our bubble. We'd still rather have people sending out madd haccs with the tools we publish.

**Comment by Lusamine** [comment]
Closing this issue since SysBot.NET is now at a more comfortable state for trading en masse online. As @kwsch stated, our priority is proper legality support to minimize risk and disruption when interacting in an online setting.

For those who came here asking for forks, please do not use this repository in the future to seek out forks. Do so at your own risk, knowing that their priorities may not match ours. I do not want to be part of it.

**Pull request closed without merging**
