### PR TITLE
Egg bot additional functionality

### PR DESCRIPTION
**Pull request by bell4631**
I had to make some corrections after realizing I made some basic mistakes with what I was trying to achieve. Hopefully, this should be more fruitful.

### CODE REVIEW

**Comment by GriffinG1** [comment]
And this required a new PR... why?

**Comment by bell4631** [comment]
@GriffinG1 My apologies; I was trying to figure out my way around the process of making pull requests. I was able to resolve all the errors/warnings just a few minutes ago.

**Comment by Lusamine** [comment]
Correct way to implement this shouldn't be to duplicate large amounts of code from another bot.  I'm not sure why the nature check is necessary either when you can breed with everstone.  I can implement IV check functionality but that feels marginally useful when you can look at the eggs collected yourself.

**Comment by Lusamine** [comment]
I extracted the EncounterBot settings in https://github.com/kwsch/SysBot.NET/commit/eb180557211502bb00ccee25cf483266553fa72c so they now work for FossilBot, EggBot, and EncounterBot.  They're now under **Operation> StopConditions**.  You can read the wiki page on [Stop Conditions](https://github.com/kwsch/SysBot.NET/wiki/Settings#stop-conditions) about how to set them.  I think that will accomplish what you're going for and increase functionality for other bots.

**Pull request closed without merging**
